### ISSUE TITLE
Develop the homepage (desktop view)

### ISSUE THREAD

**Issue by midnightplayer1412** [midnightplayer1412/task-tracker-app#3]
### Navigation Bar
**Task**
- [x] Upcoming
- [x] Today
- [ ] Calendar
- [ ] Sticky Wall

**Lists**
- [x] Design the lists content

**Tags**
- [x] Design for the tags content

**Settting**
- [x] Create the Settings UI

**Sign out**
- [x] Create the sign out function
